-- =============================================================================
-- 01-create-databases.sql
--
-- Inicialización de las bases de datos para FIM Platform.
-- Este script es ejecutado automáticamente por la imagen oficial de PostgreSQL
-- durante el PRIMER arranque del contenedor (cuando pg_data está vacío).
-- En reinicios posteriores NO se vuelve a ejecutar (comportamiento estándar
-- de docker-entrypoint-initdb.d/), por lo que no necesitamos protecciones
-- idempotentes a nivel SQL.
--
-- Contexto de ejecución:
--   - Corre conectado a la base `fim` (creada por POSTGRES_DB=fim).
--   - Corre como usuario `fim` (POSTGRES_USER=fim), que es superusuario de
--     esta instancia. Por eso puede ejecutar CREATE DATABASE sin más.
--
-- RN-67: el sistema usa UNA instancia de PostgreSQL con DOS bases separadas:
--   - fim       → base de la aplicación FIM Platform (backend FastAPI).
--                 Creada por POSTGRES_DB=fim antes de que corra este script.
--   - fim_n8n   → base exclusiva de n8n (notificaciones). Creada acá.
-- Los datos de n8n y de la aplicación NO comparten tablas. La separación es
-- a nivel de base, no de usuario (D-03).
--
-- D-03: se usa un ÚNICO usuario aplicativo `fim` como owner de ambas bases.
-- No se crea un usuario separado para n8n en M1. Ver design.md D-03 para
-- el razonamiento y el trigger de revisión.
--
-- Notas técnicas:
--   - CREATE DATABASE NO puede ejecutarse dentro de un bloque DO/función ni
--     dentro de una transacción. Por eso usamos sentencia plana, no DO $$.
--   - PostgreSQL no soporta `CREATE DATABASE IF NOT EXISTS`. Es OK porque el
--     script solo corre cuando pg_data está vacío.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Base: fim_n8n (uso exclusivo de n8n: workflows, credenciales, historial).
-- El servicio n8n recibe DB_POSTGRESDB_DATABASE=fim_n8n para que no acceda
-- jamás a la base `fim` por error de configuración.
-- Como la crea el usuario `fim`, queda como owner automáticamente.
-- -----------------------------------------------------------------------------
CREATE DATABASE fim_n8n;

-- D-03: n8n necesita ALL PRIVILEGES sobre fim_n8n para crear su propio schema,
-- tablas e índices al arrancar (migraciones internas de n8n). El GRANT es
-- redundante si `fim` ya es owner, pero lo mantenemos explícito para que
-- una rotación futura de owner (ej: usuario `n8n` separado) no rompa permisos.
GRANT ALL PRIVILEGES ON DATABASE fim_n8n TO fim;
