"""
Wrapping of the agent shared secret at rest (D86/RN-180, Change 68).

`agents.shared_secret_hex` stores `v1:<base64url(nonce || ciphertext || tag)>` instead of the
plain hex: AES-256-GCM, a fresh 12-byte nonce per wrap and AAD = `agent_id`, so a value copied
from one agent's row to another's does not decrypt. The 32-byte wrapping key lives in a file
outside the database (volume `backend_secrets`), is generated only by `certs-init` and is
loaded once by the lifespan.

`AgentSecretUnwrapError` inherits from `ValueError` on purpose: the six read sites used to
call `bytes.fromhex`, which raises `ValueError`, and each one has an error semantics fixed by
D37/RN-131 (two return `None`, one logs and discards, three propagate to roll back the outbox
transaction). Inheriting keeps every `except ValueError` and every propagation unchanged.

A value without `:` is the legacy plain hex and is still readable; any other prefix fails
closed. There is deliberately no function that rewrites the secrets in plain text: rolling
back to plaintext is not supported (RN-180). Key rotation is not supported either: the `v1:`
prefix is reserved for a future version.
"""

from __future__ import annotations

import base64
import binascii
import os
import secrets
import stat

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from sqlmodel import Session, select

from app.core.logging import log
from app.modules.agents.models import Agent

_PREFIX_V1 = "v1:"
_NONCE_LEN = 12
_SECRET_LEN = 32
_KEY_LEN = 32

# Process-wide key, set by `load_wrap_key` (lifespan, or the test harness).
_wrap_key: bytes | None = None


class AgentSecretUnwrapError(ValueError):
    """The stored agent secret cannot be unwrapped. Never carries secret or key material."""


def _require_key() -> bytes:
    if _wrap_key is None:
        # A programming error, not a data error: deliberately not a ValueError.
        raise RuntimeError("agent secret wrap key is not loaded (call load_wrap_key first)")
    return _wrap_key


def wrap_agent_secret(agent_id: str, secret: bytes) -> str:
    """Wrap the 32-byte shared secret for `agent_id` into the `v1:` storage format."""
    if len(secret) != _SECRET_LEN:
        raise ValueError(f"agent secret must be {_SECRET_LEN} bytes")
    nonce = os.urandom(_NONCE_LEN)
    ciphertext = AESGCM(_require_key()).encrypt(nonce, secret, agent_id.encode("utf-8"))
    payload = base64.urlsafe_b64encode(nonce + ciphertext).rstrip(b"=").decode("ascii")
    return _PREFIX_V1 + payload


def unwrap_agent_secret(agent_id: str, stored: str) -> bytes:
    """Return the shared secret bytes from a stored value (`v1:` wrapped or legacy hex).

    Every failure raises `AgentSecretUnwrapError`; the message never includes the stored value.
    """
    if stored.startswith(_PREFIX_V1):
        key = _require_key()
        try:
            payload = stored[len(_PREFIX_V1):]
            raw = base64.urlsafe_b64decode(payload + "=" * (-len(payload) % 4))
            if len(raw) <= _NONCE_LEN:
                raise AgentSecretUnwrapError("wrapped agent secret is truncated")
            secret = AESGCM(key).decrypt(raw[:_NONCE_LEN], raw[_NONCE_LEN:], agent_id.encode("utf-8"))
        except (binascii.Error, InvalidTag, ValueError) as exc:
            if isinstance(exc, AgentSecretUnwrapError):
                raise
            raise AgentSecretUnwrapError("wrapped agent secret cannot be unwrapped") from None
    elif ":" in stored:
        raise AgentSecretUnwrapError("unknown agent secret storage format")
    else:
        try:
            return bytes.fromhex(stored)
        except ValueError:
            raise AgentSecretUnwrapError("legacy agent secret is not valid hex") from None

    if len(secret) != _SECRET_LEN:
        raise AgentSecretUnwrapError("unwrapped agent secret has an unexpected length")
    return secret


def _key_invalid(path: str, reason: str) -> RuntimeError:
    log.error("backend.agent_secret_wrap_key.invalid", path=path, reason=reason)
    return RuntimeError(
        f"agent secret wrap key invalid: path={path!r} reason={reason} "
        "(the key is generated by certs-init in the backend_secrets volume)"
    )


def load_wrap_key(path: str) -> None:
    """Load and validate the wrapping key file. Raises `RuntimeError` on any problem.

    Causes: `not_configured`, `missing`, `unreadable`, `invalid_length`, `permissive_mode`
    (any of the bits `0o177` set: looser than `0400`/`0600`). The file content is never logged.
    The previously loaded key, if any, is left untouched on failure.
    """
    global _wrap_key
    if not path:
        raise _key_invalid(path, "not_configured")
    try:
        mode = os.stat(path).st_mode
    except FileNotFoundError:
        raise _key_invalid(path, "missing") from None
    except OSError:
        raise _key_invalid(path, "unreadable") from None
    if not stat.S_ISREG(mode):
        raise _key_invalid(path, "unreadable")
    if mode & 0o177:
        raise _key_invalid(path, "permissive_mode")
    try:
        with open(path, "rb") as fh:
            key = fh.read(_KEY_LEN + 1)
    except OSError:
        raise _key_invalid(path, "unreadable") from None
    if len(key) != _KEY_LEN:
        raise _key_invalid(path, "invalid_length")
    _wrap_key = key
    log.info("backend.agent_secret_wrap_key.loaded", path=path)


def ensure_wrap_key_file(path: str) -> None:
    """Create the wrapping key file if missing; never overwrite an existing one (`certs-init`).

    A missing file is created exclusively (`O_EXCL`) with 32 random bytes and mode `0400`.
    An existing 32-byte file is left alone; any other length raises and is not modified: a
    regenerated key would make every wrapped secret unreadable.
    """
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    try:
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o400)
    except FileExistsError:
        size = os.stat(path).st_size
        if size != _KEY_LEN:
            raise RuntimeError(
                f"agent secret wrap key at {path!r} has {size} bytes, expected {_KEY_LEN}; "
                "refusing to touch it"
            ) from None
        return
    try:
        os.write(fd, secrets.token_bytes(_KEY_LEN))
    finally:
        os.close(fd)


def wrap_legacy_agent_secrets(session: Session) -> int:
    """Wrap every legacy plain-hex secret in a single transaction; return how many were wrapped.

    Idempotent startup reconciliation (not a schema migration, outside D84/RN-178). Rows with
    a NULL secret or already `v1:` are not selected. A row whose hex is invalid is left intact
    and reported by `agent_id`: it is already unreadable for every read site, and aborting would
    leave every healthy agent without a backend.
    """
    rows = session.exec(
        select(Agent).where(
            Agent.shared_secret_hex.isnot(None),  # type: ignore[union-attr]
            ~Agent.shared_secret_hex.like(f"{_PREFIX_V1}%"),  # type: ignore[union-attr]
        )
    ).all()

    wrapped = 0
    skipped_invalid = 0
    for agent in rows:
        try:
            secret = bytes.fromhex(agent.shared_secret_hex)  # type: ignore[arg-type]
            agent.shared_secret_hex = wrap_agent_secret(agent.agent_id, secret)
        except ValueError:
            skipped_invalid += 1
            log.error("agents.secret_wrap.legacy_invalid", agent_id=agent.agent_id)
            continue
        session.add(agent)
        wrapped += 1
    session.commit()
    log.info("agents.secret_wrap.migrated", wrapped=wrapped, skipped_invalid=skipped_invalid)
    return wrapped
